#!/usr/bin/env python3
"""
generate_agent_rules.py — Generates agent-specific rule files from manifest.json.

Produces activation rules for multiple AI coding assistants from a single source of truth.

Uso:
    python .agents/scripts/generate_agent_rules.py [--agent <name>]
    python .agents/scripts/generate_agent_rules.py --agent cline
    python .agents/scripts/generate_agent_rules.py  # generates all

Agentes soportados:
    - cline       → .clinerules
    - cursor      → .cursorrules (appends/overwrites agent section)
    - claude      → CLAUDE.md
    - gemini      → AGENTS.md
    - copilot     → .github/copilot-instructions.md
"""

import json
import sys
import argparse
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────────

WORKSPACE_ROOT = Path(__file__).parent.parent.parent
AGENTS_DIR = WORKSPACE_ROOT / ".agents"
MANIFEST_PATH = AGENTS_DIR / "manifest.json"

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_manifest() -> dict:
    """Load and return the manifest.json content."""
    if not MANIFEST_PATH.exists():
        print(f"[ERROR] manifest.json not found at {MANIFEST_PATH}")
        sys.exit(1)
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def build_skill_table(skills: list[dict]) -> str:
    """Build a markdown table of skills and their primary triggers."""
    lines = [
        "| Skill | Primary Triggers | Description |",
        "|-------|-----------------|-------------|",
    ]
    for skill in skills:
        name = skill.get("name", "")
        description = skill.get("description", "")
        triggers = skill.get("triggers", [])
        trigger_str = ", ".join(f'"{t}"' for t in triggers[:3])
        if len(triggers) > 3:
            trigger_str += f" (+{len(triggers) - 3} more)"
        lines.append(f"| `{name}` | {trigger_str} | {description[:60]}... |")
    return "\n".join(lines)


def build_pipelines_section(pipelines: dict) -> str:
    """Build a markdown section describing available pipelines."""
    if not pipelines:
        return ""
    lines = ["\n## Multi-Skill Pipelines\n"]
    for name, pipeline in pipelines.items():
        desc = pipeline.get("description", "")
        steps = " → ".join(f"`{s}`" for s in pipeline.get("steps", []))
        lines.append(f"- **{name}**: {desc}")
        lines.append(f"  - Steps: {steps}")
    return "\n".join(lines)

# ── Generators ────────────────────────────────────────────────────────────────

def generate_cline(manifest: dict) -> None:
    """Generate .clinerules for Cline / Roo-Code."""
    skills = manifest.get("skills", [])
    pipelines = manifest.get("pipelines", {})

    content = f"""Antes de responder o ejecutar cualquier tarea, revisa obligatoriamente el directorio `.agents/skills/`.
Consulta `.agents/manifest.json` para identificar cuál skill corresponde al contexto actual, usando la lista de `triggers` de cada skill como referencia de activación.
Una vez identificada la skill, lee su `SKILL.md` completo, adopta ese rol, sus responsabilidades, y carga sus archivos de referencia siguiendo la sección `## Reference Loading`.
Si la tarea involucra múltiples skills (ej. análisis + refactoring), actívalas secuencialmente siguiendo el orden lógico definido en los pipelines de `.agents/config.yaml`.
Lee `.agents/config.yaml` para obtener el idioma de respuesta, stacks soportados y configuración por skill.
"""

    output_path = WORKSPACE_ROOT / ".clinerules"
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {output_path.relative_to(WORKSPACE_ROOT)}")


def generate_claude(manifest: dict) -> None:
    """Generate CLAUDE.md for Claude Code."""
    skills = manifest.get("skills", [])
    pipelines = manifest.get("pipelines", {})
    skill_table = build_skill_table(skills)
    pipelines_section = build_pipelines_section(pipelines)

    content = f"""# CLAUDE.md — Agentic Workspace

> Instructions for Claude Code agent integration.
> Auto-generated by `generate_agent_rules.py` — edit manifest.json to update triggers.

## Agent Skill System

This workspace uses a **skill-based agent architecture**. Before responding to any task:

1. Read `.agents/manifest.json` to identify the applicable skill based on the user's request and the `triggers` field.
2. Read the skill's `SKILL.md` in full and adopt its role and guidelines.
3. Follow the `## Reference Loading` section in the skill to load relevant reference files.
4. For complex tasks, chain skills in order as described in `.agents/config.yaml` pipelines.

## Key Files

- `.agents/manifest.json` — Skill catalog (source of truth for triggers and metadata)
- `.agents/config.yaml` — Workspace configuration (language, pipelines, per-skill settings)
- `.agents/skills/<name>/SKILL.md` — Individual skill instructions
- `.agents/skills/<name>/references/` — Deep-dive reference documents
- `.agents/skills/<name>/examples/` — Sample outputs for format reference

## Available Skills

{skill_table}
{pipelines_section}

## Language Rule

All responses must be in the language specified in `.agents/config.yaml` → `response_language` (default: Spanish).

## Validation

After any changes to skill files, run:
```bash
python .agents/scripts/validate_skills.py
```
"""

    output_path = WORKSPACE_ROOT / "CLAUDE.md"
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {output_path.relative_to(WORKSPACE_ROOT)}")


def generate_agents_md(manifest: dict) -> None:
    """Generate AGENTS.md for Gemini Code Assist / Jules / Antigravity."""
    skills = manifest.get("skills", [])
    pipelines = manifest.get("pipelines", {})
    skill_table = build_skill_table(skills)
    pipelines_section = build_pipelines_section(pipelines)

    content = f"""# AGENTS.md — Agentic Workspace

> Activation rules for Gemini Code Assist, Jules, and Antigravity agents.
> Auto-generated by `generate_agent_rules.py` — edit manifest.json to update triggers.

## Core Instruction

Before responding to or executing any task, you MUST:

1. **Check the skills catalog**: Read `.agents/manifest.json` to identify which skill applies to the current context, using the `triggers` field of each skill as activation keywords.
2. **Load the skill**: Once a skill is identified, read its full `SKILL.md` and adopt that role, responsibilities, and guidelines.
3. **Load references**: Follow the `## Reference Loading` section in the skill to determine which reference files to read.
4. **Multi-skill tasks**: If a task spans multiple skills, activate them **sequentially in logical order** as defined in the `pipelines` section of `.agents/config.yaml`.

## Configuration

Read `.agents/config.yaml` for:
- Response language (`response_language`)
- Supported language stacks
- Per-skill behavior overrides
- Available multi-skill pipelines

## Available Skills

{skill_table}
{pipelines_section}

## Response Language

All responses must be in the language specified in `.agents/config.yaml` → `response_language` (default: **Spanish**).

## Autonomous Operation (`/goal` command)

When the `/goal` command is used:
- Operate autonomously without pausing for confirmations
- Self-correct: run tests, read errors, fix, repeat until passing
- Use subagents for parallel workstreams
- Follow the skill pipeline defined in `.agents/config.yaml`
"""

    output_path = WORKSPACE_ROOT / "AGENTS.md"
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {output_path.relative_to(WORKSPACE_ROOT)}")


def generate_copilot(manifest: dict) -> None:
    """Generate .github/copilot-instructions.md for GitHub Copilot."""
    skills = manifest.get("skills", [])
    pipelines = manifest.get("pipelines", {})
    skill_table = build_skill_table(skills)
    pipelines_section = build_pipelines_section(pipelines)

    content = f"""# GitHub Copilot Instructions — Agentic Workspace

> Auto-generated by `generate_agent_rules.py` — edit manifest.json to update.

This workspace uses a skill-based agent architecture. When assisting with tasks:

1. Identify the relevant skill from `.agents/manifest.json` using the trigger keywords.
2. Read the skill's `SKILL.md` for role definition, responsibilities, and output format.
3. Load reference files as specified in the skill's `## Reference Loading` section.

## Available Skills

{skill_table}
{pipelines_section}

## Language: Respond in Spanish (configurable via `.agents/config.yaml`).
"""

    output_path = WORKSPACE_ROOT / ".github" / "copilot-instructions.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {output_path.relative_to(WORKSPACE_ROOT)}")


# ── Main ──────────────────────────────────────────────────────────────────────

GENERATORS = {
    "cline": generate_cline,
    "claude": generate_claude,
    "gemini": generate_agents_md,
    "copilot": generate_copilot,
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate agent-specific rule files from manifest.json"
    )
    parser.add_argument(
        "--agent",
        choices=list(GENERATORS.keys()),
        help="Generate rules for a specific agent only (default: all agents)",
    )
    args = parser.parse_args()

    manifest = load_manifest()
    print(f"[*] Loaded manifest v{manifest.get('version', '?')} with {len(manifest.get('skills', []))} skills\n")

    if args.agent:
        GENERATORS[args.agent](manifest)
    else:
        for name, gen in GENERATORS.items():
            gen(manifest)

    print("\n[OK] Agent rule files generated successfully.")
    print("     Run 'python .agents/scripts/validate_skills.py' to verify skill integrity.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
