"""initial schema

Revision ID: b1f120d78cde
Revises: 
Create Date: 2026-06-06 20:04:56.418453+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1f120d78cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create users table first (no dependencies)
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('identification', sa.String(length=20), nullable=False),
        sa.Column('phone', sa.String(length=30), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('is_verified', sa.Boolean(), nullable=False, default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('identification')
    )
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_identification'), 'users', ['identification'], unique=True)

    # 2. Create zones table (depends on users)
    op.create_table('zones',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('soil_type', sa.String(length=50), nullable=True),
        sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('water_quality', sa.String(length=50), nullable=True),
        sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_user_id'), 'zones', ['user_id'], unique=False)
    op.create_index('ix_zones_user_name', 'zones', ['user_id', 'name'], unique=False)

    # 3. Create products table (no dependencies)
    op.create_table('products',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('numero_registro', sa.String(length=50), nullable=False),
        sa.Column('nombre_comercial', sa.String(length=255), nullable=False),
        sa.Column('ingrediente_activo', sa.Text(), nullable=False),
        sa.Column('categoria', sa.Enum('PLAGUICIDA', 'FERTILIZANTE', name='product_category', create_constraint=True), nullable=False),
        sa.Column('estado', sa.Enum('ACTIVO', 'CANCELADO', 'EXPIRADO', 'SUSPENDIDO', name='product_status', create_constraint=True), nullable=False, default='ACTIVO'),
        sa.Column('banda_toxicologica', sa.Enum('ROJA', 'AMARILLA', 'AZUL', 'VERDE', 'NO_APLICA', name='toxic_band', create_constraint=True), nullable=True),
        sa.Column('registrante', sa.String(length=255), nullable=True),
        sa.Column('dosis_recomendada', sa.Text(), nullable=True),
        sa.Column('intervalo_seguridad_dias', sa.Integer(), nullable=True),
        sa.Column('precio_referencia_por_litro', sa.Float(), nullable=True),
        sa.Column('cultivo_objetivo', sa.String(length=100), nullable=True),
        sa.Column('problema_objetivo', sa.String(length=100), nullable=True),
        sa.Column('embedding', postgresql.ARRAY(sa.Float), nullable=True),  # pgvector.Vector handled separately
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero_registro')
    )
    op.create_index(op.f('ix_products_categoria'), 'products', ['categoria'], unique=False)
    op.create_index('ix_products_categoria_estado', 'products', ['categoria', 'estado'], unique=False)
    op.create_index(op.f('ix_products_estado'), 'products', ['estado'], unique=False)
    op.create_index('ix_products_ingrediente_activo', 'products', ['ingrediente_activo'], unique=False)
    op.create_index(op.f('ix_products_nombre_comercial'), 'products', ['nombre_comercial'], unique=False)
    op.create_index(op.f('ix_products_numero_registro'), 'products', ['numero_registro'], unique=True)
    op.create_index('ix_products_banda_toxicologica', 'products', ['banda_toxicologica'], unique=False)

    # 4. Create distributors table (no dependencies)
    op.create_table('distributors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('correo', sa.String(length=255), nullable=True),
        sa.Column('telefono', sa.String(length=50), nullable=True),
        sa.Column('ubicacion', sa.String(length=255), nullable=True),
        sa.Column('provincia', sa.String(length=50), nullable=True),
        sa.Column('canton', sa.String(length=50), nullable=True),
        sa.Column('distrito', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_distributors_nombre', 'distributors', ['nombre'], unique=False)
    op.create_index('ix_distributors_ubicacion', 'distributors', ['provincia', 'canton'], unique=False)

    # 5. Create product_distributors association table (depends on products and distributors)
    op.create_table('product_distributors',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('distributor_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('product_id', 'distributor_id')
    )

    # 6. Create regulations table (no dependencies)
    op.create_table('regulations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('titulo', sa.String(length=500), nullable=False),
        sa.Column('tipo', sa.Enum('DECRETO', 'LEY', 'RESOLUCION', 'LISTA_PROHIBIDA', 'LMR', 'OTRO', name='regulationtype', create_constraint=True), nullable=False),
        sa.Column('fecha_publicacion', sa.String(length=20), nullable=True),
        sa.Column('fuente_url', sa.String(length=500), nullable=True),
        sa.Column('resumen', sa.Text(), nullable=True),
        sa.Column('contenido_completo', sa.Text(), nullable=True),
        sa.Column('sustancias_afectadas', sa.Text(), nullable=True),
        sa.Column('cultivos_afectados', sa.Text(), nullable=True),
        sa.Column('embedding', postgresql.ARRAY(sa.Float), nullable=True),  # pgvector.Vector handled separately
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_regulations_numero'), 'regulations', ['numero'], unique=True)
    op.create_index('ix_regulations_sustancias', 'regulations', ['sustancias_afectadas'], unique=False)
    op.create_index(op.f('ix_regulations_tipo'), 'regulations', ['tipo'], unique=False)

    # 7. Create recommendations table (depends on users, zones)
    op.create_table('recommendations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('zone_id', sa.Integer(), nullable=True),
        sa.Column('ticket_id', sa.String(length=100), nullable=False),
        sa.Column('crop', sa.String(length=100), nullable=False),
        sa.Column('crop_stage', sa.String(length=50), nullable=False),
        sa.Column('problem', sa.String(length=255), nullable=False),
        sa.Column('problem_category', sa.String(length=100), nullable=False),
        sa.Column('last_agrochemical_used', sa.String(length=255), nullable=True),
        sa.Column('budget_range', sa.String(length=50), nullable=True),
        sa.Column('soil_type', sa.String(length=50), nullable=True),
        sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('water_quality', sa.String(length=50), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='recommendation_status', create_constraint=True), nullable=False, default='PENDING'),
        sa.Column('current_step', sa.String(length=50), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_recommendations_ticket_id'), 'recommendations', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index('ix_recommendations_user_status', 'recommendations', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_recommendations_zone_id'), 'recommendations', ['zone_id'], unique=False)

    # 8. Create recommendation_products table (depends on recommendations, products)
    op.create_table('recommendation_products',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recommendation_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('justification', sa.Text(), nullable=False),
        sa.Column('dosis', sa.Text(), nullable=True),
        sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('toxicidad', sa.String(length=20), nullable=True),
        sa.Column('intervalo_seguridad', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recommendation_id', 'product_id', name='uq_recommendation_product'),
        sa.UniqueConstraint('recommendation_id', 'rank', name='uq_recommendation_rank')
    )
    op.create_index(op.f('ix_recommendation_products_product_id'), 'recommendation_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendation_products_recommendation_id'), 'recommendation_products', ['recommendation_id'], unique=False)

    # 9. Create audit_logs table (depends on users)
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'RECOMMENDATION_REQUEST', 'RECOMMENDATION_VIEW', name='audit_action', create_constraint=True), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('detail', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)

    # Create pgvector extensions and indexes for vector columns
    # The Vector type requires special handling
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # 10. Alter products to add vector column with proper type
    op.execute("ALTER TABLE products ALTER COLUMN embedding TYPE vector(768) USING embedding::vector;")
    
    # 11. Alter regulations to add vector column with proper type
    op.execute("ALTER TABLE regulations ALTER COLUMN embedding TYPE vector(768) USING embedding::vector;")

    # Create HNSW indexes for vector similarity search
    op.execute("CREATE INDEX ix_products_embedding ON products USING hnsw (embedding vector_cosine_ops);")
    op.execute("CREATE INDEX ix_regulations_embedding ON regulations USING hnsw (embedding vector_cosine_ops);")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_regulations_embedding', table_name='regulations', postgresql_using='hnsw')
    op.drop_index('ix_products_embedding', table_name='products', postgresql_using='hnsw')
    op.drop_table('audit_logs')
    op.drop_table('recommendation_products')
    op.drop_table('recommendations')
    op.drop_table('regulations')
    op.drop_table('product_distributors')
    op.drop_table('distributors')
    op.drop_table('products')
    op.drop_table('zones')
    op.drop_table('users')
    # ### end Alembic commands ###