"""increase product field lengths

Revision ID: bbc3b17fca75
Revises: b1f120d78cde
Create Date: 2026-06-06 20:13:12.954822+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbc3b17fca75'
down_revision: Union[str, None] = 'b1f120d78cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'nombre_comercial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('products', 'registrante',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_products_embedding', table_name='products', postgresql_using='hnsw')
    op.drop_constraint('products_numero_registro_key', 'products', type_='unique')
    op.alter_column('recommendations', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('recommendations_ticket_id_key', 'recommendations', type_='unique')
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.drop_index('ix_regulations_embedding', table_name='regulations', postgresql_using='hnsw')
    op.drop_constraint('regulations_numero_key', 'regulations', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_identification_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_identification_key', 'users', ['identification'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('regulations_numero_key', 'regulations', ['numero'])
    op.create_index('ix_regulations_embedding', 'regulations', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.create_unique_constraint('recommendations_ticket_id_key', 'recommendations', ['ticket_id'])
    op.alter_column('recommendations', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint('products_numero_registro_key', 'products', ['numero_registro'])
    op.create_index('ix_products_embedding', 'products', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('products', 'registrante',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('products', 'nombre_comercial',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
