"""create_lmrs_table

Revision ID: 5e5dc56e6153
Revises: 002_add_auth_user_id
Create Date: 2026-06-16 20:54:06.752045+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5dc56e6153'
down_revision: Union[str, None] = '002_add_auth_user_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lmrs',
    sa.Column('plaguicida', sa.String(length=255), nullable=False),
    sa.Column('clase', sa.String(length=255), nullable=True),
    sa.Column('cultivo', sa.String(length=500), nullable=False),
    sa.Column('lmr_nac', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lmrs_cultivo'), 'lmrs', ['cultivo'], unique=False)
    op.create_index(op.f('ix_lmrs_plaguicida'), 'lmrs', ['plaguicida'], unique=False)
    op.drop_constraint('uq_users_auth_user_id', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_auth_user_id', 'users', ['auth_user_id'])
    op.drop_index(op.f('ix_lmrs_plaguicida'), table_name='lmrs')
    op.drop_index(op.f('ix_lmrs_cultivo'), table_name='lmrs')
    op.drop_table('lmrs')
    # ### end Alembic commands ###
